service: notion-to-slack

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: handler.run
    events:
      - schedule: cron(0/5 * ? * MON-FRI *)
    environment:
      NOTION_API_KEY: ${env:NOTION_API_KEY}
      NOTION_DATABASE_ID: ${env:NOTION_DATABASE_ID}
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${env:SLACK_CHANNEL}
